name: flutter_collection
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ui
  lottie: ^1.3.0
  fluttertoast: ^8.0.9
  salomon_bottom_bar: ^3.3.1
  animated_text_kit: ^4.2.1
  flutter_fortune_wheel: ^1.2.0
  roller_list: ^1.0.2

  # state managements
  flutter_riverpod: ^1.0.3
  hooks_riverpod: ^1.0.3
  riverpod: ^1.0.3

  # api fetcher
  dio: ^4.0.6

  # di
  get_it: ^7.2.0

  # utils
  easy_localization: ^3.0.0
  google_fonts: ^3.0.1
  flutter_svg: ^1.0.3
  freezed_annotation: ^2.0.3
  qr_code_scanner: ^0.7.0
  shared_preferences: ^2.0.15

  cupertino_icons: ^1.0.2
  qr_flutter: ^4.0.0
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4
  build_runner: ^2.1.11
  freezed: ^2.0.3+1

# following page: https://dart.dev/tools/pub/pubspec

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/default/
    - assets/translations/
    - assets/ui/

  # example:
  # fonts:
  # - family: Schyler
  #   fonts:
  #     - asset: fonts/Schyler-Regular.ttf
  #     - asset: fonts/Schyler-Italic.ttf
  #       style: italic
  # - family: Trajan Pro
  #   fonts:
  #     - asset: fonts/TrajanPro.ttf
  #     - asset: fonts/TrajanPro_Bold.ttf
  #       weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
