// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOHa1cljtqDvEMbkp-SjjAcZYDH9gRQQQ',
    appId: '1:218291736554:web:b65b3540590d39fe0d2c93',
    messagingSenderId: '218291736554',
    projectId: 'flutter-collection-1b086',
    authDomain: 'flutter-collection-1b086.firebaseapp.com',
    storageBucket: 'flutter-collection-1b086.appspot.com',
    measurementId: 'G-73FJM3RW7H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDVQpqHHiSMB4wAlxil1xEeBDPruefYIf4',
    appId: '1:218291736554:android:43168b749c0c3bbf0d2c93',
    messagingSenderId: '218291736554',
    projectId: 'flutter-collection-1b086',
    storageBucket: 'flutter-collection-1b086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-Hngp4L-L6hNM-ifKvRtoM_CA4a5Rdio',
    appId: '1:218291736554:ios:4b42cc154287bdcd0d2c93',
    messagingSenderId: '218291736554',
    projectId: 'flutter-collection-1b086',
    storageBucket: 'flutter-collection-1b086.appspot.com',
    iosClientId: '218291736554-mod4ccgb1o5ualhok0r9b2mqngqjh86v.apps.googleusercontent.com',
    iosBundleId: 'app.grushenka.flutterCollection',
  );
}
